import React from 'react';
import { PageLayout } from '@/components/landing/PageLayout';

export const metadata = {
    title: 'Terms of Service – Vignova',
    description: 'Vignova terms of service. Understand the rules and guidelines for using our platform.',
};

export default function TermsPage() {
    return (
        <PageLayout>
            <article className="max-w-3xl">
                <h1 className="text-4xl md:text-5xl font-bold text-slate-900 tracking-tight mb-6">
                    Terms of Service
                </h1>
                <p className="text-slate-500 text-lg mb-12">
                    Last updated: March 14, 2026
                </p>

                <div className="space-y-10 text-slate-600 leading-relaxed">
                    <section>
                        <h2 className="text-xl font-bold text-slate-900 mb-4">1. Acceptance of Terms</h2>
                        <p>
                            By accessing or using Vignova (&quot;the Service&quot;), you agree to be bound by these Terms of Service.
                            If you do not agree to these terms, please do not use the Service. Vignova reserves the right
                            to modify these terms at any time, and continued use constitutes acceptance of updated terms.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-xl font-bold text-slate-900 mb-4">2. Service Description</h2>
                        <p>
                            Vignova is an AI-powered career platform that provides resume generation, ATS optimization,
                            job application tracking, and browser extension services. The platform uses artificial intelligence
                            to help job seekers create tailored resumes and manage their job search process.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-xl font-bold text-slate-900 mb-4">3. User Accounts</h2>
                        <ul className="list-disc list-inside space-y-2 pl-4 text-slate-500">
                            <li>You must provide accurate and complete information when creating an account.</li>
                            <li>You are responsible for maintaining the security of your account credentials.</li>
                            <li>You must be at least 16 years old to use the Service.</li>
                            <li>One person may not maintain more than one account.</li>
                        </ul>
                    </section>

                    <section>
                        <h2 className="text-xl font-bold text-slate-900 mb-4">4. Acceptable Use</h2>
                        <p className="mb-4">You agree not to:</p>
                        <ul className="list-disc list-inside space-y-2 pl-4 text-slate-500">
                            <li>Use the Service for any unlawful purpose or to create fraudulent resumes.</li>
                            <li>Attempt to reverse-engineer, decompile, or exploit our AI systems.</li>
                            <li>Share your account credentials with third parties.</li>
                            <li>Use automated tools to scrape or extract data from the Service.</li>
                            <li>Upload malicious content or attempt to compromise our systems.</li>
                        </ul>
                    </section>

                    <section>
                        <h2 className="text-xl font-bold text-slate-900 mb-4">5. AI-Generated Content</h2>
                        <p>
                            Vignova uses AI to generate resume content and provide recommendations. While we strive for
                            accuracy, AI-generated content should be reviewed by you before use. You are ultimately
                            responsible for the accuracy and truthfulness of information in your resumes.
                            Vignova does not guarantee job placement or interview outcomes.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-xl font-bold text-slate-900 mb-4">6. Intellectual Property</h2>
                        <p>
                            You retain ownership of all personal content and career information you provide to the Service.
                            Resumes generated by the Service are yours to use freely. Vignova retains ownership of its
                            platform, AI models, templates, and proprietary technology.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-xl font-bold text-slate-900 mb-4">7. Subscription & Credits</h2>
                        <p>
                            Certain features of Vignova require a subscription or credits. Credit-based features are
                            consumed upon use and are non-refundable once used. Subscription plans auto-renew unless
                            cancelled before the renewal date. Refund requests for unused subscription periods may
                            be considered on a case-by-case basis.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-xl font-bold text-slate-900 mb-4">8. Limitation of Liability</h2>
                        <p>
                            Vignova is provided &quot;as is&quot; without warranties of any kind. We are not liable for any
                            indirect, incidental, or consequential damages arising from your use of the Service.
                            Our total liability shall not exceed the amount you paid for the Service in the
                            twelve months preceding the claim.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-xl font-bold text-slate-900 mb-4">9. Termination</h2>
                        <p>
                            We may suspend or terminate your account if you violate these terms. You may delete your
                            account at any time. Upon termination, your data will be deleted in accordance with our
                            Privacy Policy.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-xl font-bold text-slate-900 mb-4">10. Contact</h2>
                        <p>
                            For any questions about these terms, contact us at{' '}
                            <a href="mailto:hello@vignova.io" className="text-blue-600 hover:underline">hello@vignova.io</a>.
                        </p>
                    </section>
                </div>
            </article>
        </PageLayout>
    );
}
