const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const app=path.resolve(__dirname,'../resume-saas-v4');
const appRequire=require('node:module').createRequire(path.join(app,'package.json'));
const ts=appRequire('typescript');
function load(file,overrides={}){const filename=path.join(app,file),module={exports:{}};const {outputText}=ts.transpileModule(fs.readFileSync(filename,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020,esModuleInterop:true}});vm.runInThisContext('(function(require,module,exports){'+outputText+'\n})',{filename})(name=>Object.hasOwn(overrides,name)?overrides[name]:appRequire(name),module,module.exports);return module.exports;}
const cors=load('lib/extensionCors.ts');
const plan=load('lib/extensionPlan.ts',{'@/lib/extensionCors':cors});
const USER='00000000-0000-4000-8000-000000000001';
const input={jobTitle:'Software Engineer',company:'Example',jobDescription:'Build reliable distributed applications with Python and SQL, collaborate with product teams and review code.'};
function harness({planType='PRO',balance=4,error=null,existingJob=null}={}){
    const calls=[];let available=balance,failModel=false,failSave=false,settings={templateId:'modern',jobAlerts:{enabled:true,keyword:'Engineer',location:'Dublin'}};
    const db={
        savedInterview:{create:async args=>{calls.push(['save',args]);if(failSave)throw Error('database unavailable');return {id:'interview1'};}},
        master_profiles:{findFirst:async args=>{calls.push(['profile',args]);return {parsed_data:{fullName:'Example Person',skills:['Python']}};}},
        users:{findUnique:async args=>{calls.push(['user',args]);return {extensionSettings:settings};}},
        $executeRaw:async(strings,...values)=>{calls.push(['merge',strings.join('?'),values]);settings={...settings,...JSON.parse(values[0])};},
        jobApplication:{findMany:async args=>{calls.push(['jobs',args]);return [{id:'job1',jobTitle:'Engineer',_count:{generatedResumes:1,atsReports:0}}];},count:async args=>{calls.push(['count',args]);return 3;}},
        generatedResume:{create:async args=>{calls.push(['saveResume',args]);if(failSave)throw Error('save failed');return {id:'resume1'};},count:async args=>{calls.push(['resumes',args]);return 2;}},
        jobs:{findMany:async args=>{calls.push(['feed',args]);return [{id:'feed1',title:'Engineer'}];}}
    };
    db.master_profiles.findMany=async()=>[{is_default:true,parsed_data:{fullName:'Example Person',skills:['Python'],experience:[]}}];
    db.jobApplication.create=async args=>{calls.push(['createJob',args]);return {id:'job1'};};
    db.jobApplication.update=async args=>{calls.push(['updateJob',args]);return {id:'job1'};};
    const shared=load('lib/extensionDashboard.ts',{'@/lib/db':{db}});
    const overrides={'@/lib/db':{db},'@/components/resume-html-templates':{getTemplateGenerator:()=>()=>'<html>Resume</html>'},'@/lib/pdf/puppeteer':{generatePdfFromHtml:async()=>Buffer.from('%PDF-1.4 fixture')},'@/lib/extensionDuplicate':{findExistingWork:async()=>null,findJobByUrl:async()=>existingJob,duplicateResponse:()=>({duplicate:true})},'@/lib/tailoredResume':{toResumeData:data=>data},'@/lib/extensionCors':cors,'@/lib/extensionPlan':plan,'@/lib/extensionDashboard':shared,
        '@/lib/extensionAuth':{getExtensionUser:async()=>error?{error,status:401}:{user:{id:USER,extensionSettings:settings},subscription:{plan_type:planType,credits_remaining:balance},status:200}},
        '@/lib/credits':{spendCredit:async id=>{calls.push(['spend',id]);if(available<=0)return {ok:false,reason:'insufficient'};return {ok:true,remaining:--available};},refundCredit:async id=>{calls.push(['refund',id]);available++;}},
        '@/lib/career-ops':{callBackend:async(url,args)=>{calls.push(['model',url,args]);return failModel?{ok:false}:url==='/api/score-job'?{ok:true,data:{score:75,breakdown:{matching_keywords:['Python'],missing_keywords:['SQL']}}}:url==='/api/generate-tailored-resume'?{ok:true,data:{data:{fullName:'Example Person',summary:'Experienced engineer'}}}:url.includes('generate-')?{ok:true,data:{response:'Generated document content.'}}:{ok:true,data:{questions:[{question:'How would you monitor a deployed service?',tip:'Discuss metrics and alerting.'}]}};}}
    };
    return {calls,db,shared,route:name=>load('app/api/extension/'+name+'/route.ts',overrides),balance:()=>available,failModel:()=>failModel=true,failSave:()=>failSave=true,settings:()=>settings};
}
const request=(body=input)=>new Request('https://app.vignova.io/api/extension/interview-prep',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});
test('interview API rejects missing auth before database or AI work',async()=>{const h=harness({error:'Missing token'});assert.equal((await h.route('interview-prep').POST(request())).status,401);assert.equal(h.calls.length,0);});
for(const [planType,balance] of [['FREE',20],['PRO',0],['PREMIUM',0]])test(planType+' with '+balance+' credits cannot bypass paid interview API',async()=>{const h=harness({planType,balance});const r=await h.route('interview-prep').POST(request());assert.equal(r.status,402);assert.equal((await r.json()).upgradeRequired,true);assert.equal(h.calls.length,0);});
test('interview validates input without spending a credit',async()=>{const h=harness();assert.equal((await h.route('interview-prep').POST(request({...input,jobDescription:'short'}))).status,400);assert.equal(h.balance(),4);assert.equal(h.calls.length,0);});
test('interview reserves first and saves questions under the authenticated user',async()=>{const h=harness();const r=await h.route('interview-prep').POST(request({...input,userId:'attacker-supplied'}));assert.equal(r.status,200);const body=await r.json();assert.equal(body.credits_remaining,3);assert.equal(body.interviewId,'interview1');assert.ok(h.calls.findIndex(c=>c[0]==='spend')<h.calls.findIndex(c=>c[0]==='model'));assert.equal(h.calls.find(c=>c[0]==='save')[1].data.userId,USER);assert.equal(h.calls.find(c=>c[0]==='profile')[1].where.user_id,USER);});
for(const failure of ['failModel','failSave'])test('interview refunds its reservation on '+failure,async()=>{const h=harness();h[failure]();assert.equal((await h.route('interview-prep').POST(request())).status,502);assert.equal(h.balance(),4);assert.equal(h.calls.filter(c=>c[0]==='refund').length,1);});
test('concurrent final-credit requests invoke the model only once',async()=>{const h=harness({balance:1}),route=h.route('interview-prep');const responses=await Promise.all([route.POST(request()),route.POST(request())]);assert.deepEqual(responses.map(r=>r.status).sort(),[200,402]);assert.equal(h.calls.filter(c=>c[0]==='model').length,1);assert.equal(h.balance(),0);});
test('overview is free and every activity query is scoped to the current user',async()=>{const h=harness({planType:'FREE'});const r=await h.route('overview').GET(new Request('https://app.vignova.io/api/extension/overview'));assert.equal(r.status,200);assert.equal(r.headers.get('Cache-Control'),'no-store');const body=await r.json();assert.equal(body.jobs[0].hasResume,true);assert.equal(body.stats.resumes,2);for(const c of h.calls)assert.equal(c[1].where.userId,USER);});
test('UTC week starts Monday, including on Sunday',()=>{const h=harness();assert.equal(h.shared.startOfWeek(new Date('2026-09-13T23:59:00Z')).toISOString(),'2026-09-07T00:00:00.000Z');});
test('pasting a job without a URL creates a new record and saves the company logo',async()=>{const h=harness();let created,lookups=0;h.db.jobApplication.findFirst=async()=>{lookups++;return {id:'unrelated'};};h.db.jobApplication.create=async args=>{created=args.data;return {id:'new-job'};};const route=load('app/api/extension/save-job/route.ts',{'@/lib/db':{db:h.db},'@/lib/extensionAuth':{getExtensionUser:async()=>({user:{id:USER}})},'@/lib/extensionCors':cors,'@/lib/companyLogo':{safeCompanyLogo:v=>v},'@/lib/jdFormatQueue':{queueJdFormat:()=>{}}});const logo='https://media.newjobs.com/example-logo.png';const r=await route.POST(request({jobTitle:'Engineer',company:'Example',description:input.jobDescription,companyLogo:logo}));assert.equal(r.status,200);assert.equal(lookups,0);assert.equal(created.userId,USER);assert.equal(created.companyLogo,logo);});
test('expired plans and inactive accounts cannot use stale paid entitlements',async()=>{let status='ACTIVE',expires=new Date(Date.now()-1000);const auth=load('lib/extensionAuth.ts',{'jsonwebtoken':{verify:()=>({type:'extension',userId:USER})},'@/lib/db':{db:{users:{findUnique:async()=>({id:USER,status})},subscriptions:{findFirst:async()=>({id:'sub1',user_id:USER,plan_type:'PREMIUM',credits_remaining:20,expires_at:expires})}}}});const old=process.env.EXTENSION_JWT_SECRET;process.env.EXTENSION_JWT_SECRET='test-only-secret';try{const req=new Request('https://app.vignova.io',{headers:{Authorization:'Bearer test'}});const expired=await auth.getExtensionUser(req);assert.equal(expired.subscription.plan_type,'FREE');assert.equal(expired.subscription.credits_remaining,0);expires=null;assert.equal((await auth.getExtensionUser(req)).subscription.plan_type,'PREMIUM');status='SUSPENDED';assert.equal((await auth.getExtensionUser(req)).status,403);}finally{if(old===undefined)delete process.env.EXTENSION_JWT_SECRET;else process.env.EXTENSION_JWT_SECRET=old;}});

for(const name of ['generate','generate-all']){
 test(name+' blocks a free account before invoking AI',async()=>{const h=harness({planType:'FREE',balance:10});assert.equal((await h.route(name).POST(request(input))).status,402);assert.equal(h.calls.filter(c=>c[0]==='model').length,0);});
 test(name+' reserves the final credit atomically and forwards candidate focus',async()=>{const h=harness({balance:1}),route=h.route(name);const r=await Promise.all([route.POST(request({...input,hint:'Emphasize Python projects'})),route.POST(request(input))]);assert.deepEqual(r.map(x=>x.status).sort(),[200,402]);assert.equal(h.balance(),0);const model=h.calls.find(c=>c[0]==='model');assert.ok(h.calls.findIndex(c=>c[0]==='spend')<h.calls.indexOf(model));assert.match(model[2].body.jobDescription,/Emphasize Python projects/);assert.equal(h.calls.filter(c=>c[0]==='saveResume').length,1);});
 test(name+' refunds on failed AI output',async()=>{const h=harness();h.failModel();assert.equal((await h.route(name).POST(request(input))).status,502);assert.equal(h.balance(),4);assert.equal(h.calls.filter(c=>c[0]==='refund').length,1);});
}
test('cover letter spends one credit, uses the shared AI backend and returns the new balance',async()=>{const h=harness();const r=await h.route('cover-letter').POST(request({...input,description:input.jobDescription}));assert.equal(r.status,200);const body=await r.json();assert.equal(body.coverLetter,'Generated document content.');assert.equal(body.credits_remaining,3);assert.equal(h.balance(),3);const call=h.calls.find(c=>c[0]==='model');assert.ok(h.calls.findIndex(c=>c[0]==='spend')<h.calls.indexOf(call));assert.equal(call[1],'/api/generate-cover-letter');assert.equal(call[2].body.masterProfile.fullName,'Example Person');});
test('cover letter refunds its credit when generation fails',async()=>{const h=harness();h.failModel();const r=await h.route('cover-letter').POST(request({...input,description:input.jobDescription}));assert.equal(r.status,502);assert.equal(h.balance(),4);assert.equal(h.calls.filter(c=>c[0]==='refund').length,1);});
test('cover letter reuses existing text without spending another credit',async()=>{const h=harness({existingJob:{id:'job1',jobTitle:'Software Engineer',company:'Example',coverLetter:'Existing cover letter',createdAt:new Date(),updatedAt:new Date()}});const r=await h.route('cover-letter').POST(request({...input,description:input.jobDescription,jobUrl:'https://example.test/job'}));assert.equal(r.status,200);const body=await r.json();assert.equal(body.reused,true);assert.equal(body.coverLetter,'Existing cover letter');assert.equal(h.balance(),4);assert.equal(h.calls.filter(c=>c[0]==='spend'||c[0]==='model').length,0);});
test('keyword analysis stays free and returns actual backend keyword lists',async()=>{const h=harness({planType:'FREE',balance:0});const r=await h.route('score').POST(request(input));assert.equal(r.status,200);const body=await r.json();assert.deepEqual(body.breakdown.matching_keywords,['Python']);assert.equal(h.calls.filter(c=>c[0]==='spend').length,0);});
